ДЗ2
htmlacademy-javascript/359327-kekstagram-23 pull request #2
Opened 2021-06-02 15:42 UTC by korandrey

Чем заменить console.log в первой функции - не придумал

2021-06-03 08:35 UTC, babtshe requested changes

2021-06-03 08:35 UTC, babtshe commented on js/main.js
> +  min = Math.ceil(min);
если округлять вверх, могут быть ситуации, когда результат выйдет за верхнюю границу диапазона.

2021-06-03 08:35 UTC, babtshe commented on js/main.js
> +    console.log('Вы ввели значение меньше нуля. Введите корректное значение.');
Обрати внимание, что вывод в консоль линтер не пропускает. Это сделано не случайно. Вывод в консоль можно использовать для какой-то ситуативной отладки или вывода информации для конечного пользователя в редких случаях. Если есть необходимость вывести ошибку, есть специальная сущность `Error`.

Кстати, в качестве альтернативы можно не выкидывать сообщение об ошибке, а просто исправить входные данные так, чтобы они стали корректными. Право на жизнь имеют оба подхода.

2021-06-03 08:35 UTC, babtshe commented on js/main.js
> +    console.log('min и max равны. Так нельзя');
а почему так нельзя?

2021-06-03 08:35 UTC, babtshe commented on js/main.js
> +function checkMaxLenghtString(text, maxLenght) {
опечатка в названии, + стоит обратить внимание на порядок слов.

2021-06-03 08:40 UTC, korandrey commented on js/main.js
> +    console.log('min и max равны. Так нельзя');
Нет, ну так можно, но ведь тогда функция теряет смысл.

2021-06-03 08:41 UTC, korandrey commented on js/main.js
> +    console.log('min > max.Некорректно');
в теле ифа if (min > max) поменять местами переменные мин и макс?

2021-06-03 08:42 UTC, korandrey commented on js/main.js
> +    console.log('Вы ввели значение меньше нуля. Введите корректное значение.');
Думал об еррор, но мы ведь его еще не проходили, поэтому подумал, что не зачтется инициатива

2021-06-03 08:44 UTC, korandrey commented on js/main.js
> +  min = Math.ceil(min);
это в том случае, если мин = макс. а на такой исход есть иф

2021-06-03 09:27 UTC, babtshe commented on js/main.js
> +    console.log('Вы ввели значение меньше нуля. Введите корректное значение.');
Нет, тут не как в школе. Если про что-то не рассказывали на курсе, это не повод не применять. Если нет явных ограничений по критериям или правилам линтера на использование каких-то штук, ими можно пользоваться.

2021-06-03 09:27 UTC, babtshe commented on js/main.js
> +    console.log('min и max равны. Так нельзя');
Если так можно, то зачем условие? В требованиях нигде не указано, что случайных чисел должно быть несколько в каждом диапазоне.

2021-06-03 22:43 UTC, korandrey commented on js/main.js
> +  min = Math.ceil(min);
Исправил в следующем коммите

2021-06-04 08:54 UTC, babtshe requested changes

2021-06-04 08:54 UTC, babtshe commented on js/main.js
> +function MaxLengthStringCheck(text, maxLength) {
см [критерий](https://up.htmlacademy.ru/javascript/23/criteries#b8)
`checkStringMaxLength`

2021-06-04 16:24 UTC, babtshe approved these changes

2021-06-04 16:24 UTC, merged